#!/usr/bin/env bash
# build-qemu.sh
#
# Builds a bootable QEMU ARM image (core-image-minimal, MACHINE=qemuarm)
# in a separate build directory so it does not interfere with the STM32MP
# myd-yf13x build in /workdir/build.
#
# Output:
#   /workdir/build-qemu/tmp/deploy/images/qemuarm/
#       core-image-minimal-qemuarm.ext4   — root filesystem
#       zImage                             — kernel
#       *.dtb                              — device tree
#
# To run after building:
#   devcontainer exec --workspace-folder . bash /workdir/.devcontainer/scripts/run-qemu.sh
#   or from inside the container:
#   runqemu qemuarm core-image-minimal nographic
# ---------------------------------------------------------------------------
set -euo pipefail

WORKDIR=/workdir
BUILD_DIR="${WORKDIR}/build-qemu"
POKY_DIR="${WORKDIR}/poky"

BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
RED='\033[0;31m'; CYAN='\033[0;36m'; RESET='\033[0m'
log()     { echo -e "\n${GREEN}[qemu-build]${RESET} ${BOLD}$*${RESET}"; }
section() {
    echo -e "\n${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${CYAN} $*${RESET}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
}
fail()    { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }

# ── Sanity checks ─────────────────────────────────────────────────────────────
[[ -d "${POKY_DIR}" ]] || fail "poky not found at ${POKY_DIR}. Run setup-layers.sh first."
[[ "$(id -u)" -eq 0 ]] && fail "Do not run as root. BitBake will refuse."

# ── 1. Initialise a fresh QEMU build directory ────────────────────────────────
section "Step 1/3 · Initialising QEMU build environment in ${BUILD_DIR}"
cd "${POKY_DIR}"
set +u
# shellcheck disable=SC1091
source oe-init-build-env "${BUILD_DIR}"
set -u
# We are now in BUILD_DIR; bblayers.conf was auto-generated by oe-init-build-env.

NCPUS="$(nproc)"

# ── 2. Register extra layers needed for nftables ──────────────────────────────
section "Step 2/3 · Registering extra layers"

add_if_missing() {
    local path="$1"
    local name; name="$(basename "${path}")"
    if bitbake-layers show-layers 2>/dev/null | awk '{print $1}' | grep -qx "${name}"; then
        log "  already registered: ${name}"
    else
        log "  adding layer: ${name}"
        bitbake-layers add-layer "${path}"
    fi
}

# meta-oe and meta-python are dependencies of meta-networking
add_if_missing "${WORKDIR}/meta-openembedded/meta-oe"
add_if_missing "${WORKDIR}/meta-openembedded/meta-python"
add_if_missing "${WORKDIR}/meta-openembedded/meta-networking"
# meta-myir-stm32mp holds all project-local recipes (nftables-config, kernel
# config fragments, etc.) — must be present in every build so IMAGE_INSTALL
# additions in image-policy.sh resolve correctly regardless of MACHINE.
add_if_missing "${WORKDIR}/meta-myir-stm32mp"

# ── 3. Write local.conf for qemuarm ───────────────────────────────────────────
section "Step 3/3 · Writing build-qemu/conf/local.conf"

LOCAL_CONF="${BUILD_DIR}/conf/local.conf"

# Helper: delete existing assignment, append fresh one.
conf_set() {
    local key="$1" val="$2"
    sed -i "/^${key}[[:space:]]*[?:+!]*=/d" "${LOCAL_CONF}" 2>/dev/null || true
    echo "${key} = \"${val}\"" >> "${LOCAL_CONF}"
}

conf_set MACHINE          "qemuarm"
conf_set DISTRO           "poky"
conf_set CONF_VERSION     "2"

# Explicitly pin TMPDIR so QEMU and STM32 build trees never share temp files
# (default is already ${BUILDDIR}/tmp but we make it explicit here).
conf_set TMPDIR           "${BUILD_DIR}/tmp"

# Shared caches with the STM32MP build — saves re-downloading common packages.
conf_set DL_DIR           "/workdir/yocto-downloads"
conf_set SSTATE_DIR       "/workdir/yocto-sstate-cache"

conf_set BB_NUMBER_THREADS "${NCPUS}"
conf_set PARALLEL_MAKE     "-j${NCPUS}"

# Use a compact image format readable by runqemu directly.
# ext4 gives a mountable rootfs; wic gives a full-disk image.
echo 'IMAGE_FSTYPES = "ext4 tar.bz2"' >> "${LOCAL_CONF}"

# Fix: glibc configure doesn't receive --with-pkgversion, leaving PKGVERSION as
# '#undef' in config.h.  version.c uses it without an #ifdef guard, causing a
# compile error.  Provide a value so configure defines it as a string literal.
echo 'GLIBC_EXTRA_OECONF:append = " --with-pkgversion=Poky"' >> "${LOCAL_CONF}"

# Fix: bitbake's auto hash-equivalence server uses a Unix socket that can become
# unavailable under certain conditions, causing sstate_task_postfunc to fail even
# when the actual task work succeeded.  Disabling it (OEBasicHash instead of
# OEEquivHash) avoids this entirely; sstate still works, just without hash-
# equivalence deduplication across different task hashes.
echo 'BB_HASHSERVE = ""' >> "${LOCAL_CONF}"
echo 'BB_SIGNATURE_HANDLER = "OEBasicHash"' >> "${LOCAL_CONF}"

# ── Packages installed in all images (single source of truth) ───────────────
# shellcheck source=image-policy.sh
source "$(dirname "${BASH_SOURCE[0]}")/image-policy.sh"

log "local.conf written with MACHINE=qemuarm"

# ── Build core-image-minimal ──────────────────────────────────────────────────
section "Building core-image-minimal for qemuarm"
log "bitbake core-image-minimal"

START_TIME=$(date +%s)
bitbake core-image-minimal
END_TIME=$(date +%s)

ELAPSED=$(( END_TIME - START_TIME ))
HOURS=$(( ELAPSED / 3600 ))
MINS=$(( (ELAPSED % 3600) / 60 ))
SECS=$(( ELAPSED % 60 ))

DEPLOY_DIR="${BUILD_DIR}/tmp/deploy/images/qemuarm"

echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${GREEN}║   QEMU BUILD COMPLETE                                        ║${RESET}"
echo -e "${BOLD}${GREEN}╠══════════════════════════════════════════════════════════════╣${RESET}"
printf  "${BOLD}${GREEN}║${RESET}  Elapsed  : %02dh %02dm %02ds\n" "${HOURS}" "${MINS}" "${SECS}"
echo -e "${BOLD}${GREEN}║${RESET}  Deploy   : ${DEPLOY_DIR}"
echo -e "${BOLD}${GREEN}╠══════════════════════════════════════════════════════════════╣${RESET}"
echo -e "${BOLD}${GREEN}║${RESET}  Artefacts:"
ls -1 "${DEPLOY_DIR}/" 2>/dev/null | grep -E "zImage|\.dtb|\.ext4|\.wic" \
    | sed "s|^|  ${BOLD}${GREEN}║${RESET}    |" || true
echo -e "${BOLD}${GREEN}╠══════════════════════════════════════════════════════════════╣${RESET}"
echo -e "${BOLD}${GREEN}║${RESET}  To run (inside container, no display needed):"
echo -e "${BOLD}${GREEN}║${RESET}    bash /workdir/.devcontainer/scripts/run-qemu.sh"
echo -e "${BOLD}${GREEN}║${RESET}  or:"
echo -e "${BOLD}${GREEN}║${RESET}    cd /workdir/poky && source oe-init-build-env /workdir/build-qemu"
echo -e "${BOLD}${GREEN}║${RESET}    runqemu qemuarm core-image-minimal nographic"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════════════════╝${RESET}"
